config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  root 'static_pages#home'
  get  '/current_user',    to: 'users#show'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = current_user.addresses.order(:id)

    respond_to do |format|
      format.json { render json: @addresses }
      format.html
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    respond_to do |format|
      format.json { render json: @address}
      format.html
    end
  end

  # GET /addresses/new
  def new
    @address = current_user.addresses.build
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = current_user.addresses.build(address_params)

    respond_to do |format|
      if @address.save
        format.json { render json: @address }
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
      else
        format.json { render json: @address.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = current_user.addresses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:first_name, :last_name, :address1, :address2, :city, :state, :zip_code, :country,
                                      :birthday, :note, :color, :age, :website, :phone, :interest_climb, :interest_dance, :interest_read)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render json: current_user
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper

  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h4>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :first_name, class: 'col-form-label col-4 col-md-3' %>
    <%= f.text_field :first_name, class: 'form-control col' %>
  </div>

  <div class="form-group row">
    <%= f.label :last_name, class: 'col-form-label col-4 col-md-3' %>
    <%= f.text_field :last_name, class: 'form-control col' %>
  </div>

  <div class="form-group row">
    <%= f.label :address1, class: 'col-form-label col-4 col-md-3', for: 'address_street_address' %>
    <%= f.text_field :address1, class: 'form-control col', id: 'address_street_address' %>
  </div>

  <div class="form-group row">
    <%= f.label :address2, class: 'col-form-label col-4 col-md-3', for: 'address_secondary_address' %>
    <%= f.text_field :address2, class: 'form-control col', id: 'address_secondary_address' %>
  </div>

  <div class="form-group row">
    <%= f.label :city, class: 'col-form-label col-4 col-md-3' %>
    <%= f.text_field :city, class: 'form-control col' %>
  </div>

  <div class="form-group row">
    <%= f.label :state, class: 'col-form-label col-4 col-md-3' %>
    <%= f.select :state, options_for_select(us_states), class: 'form-control col' %>
  </div>

  <div class="form-group row">
    <%= f.label :zip_code, class: 'col-form-label col-4 col-md-3' %>
    <%= f.text_field :zip_code, class: 'form-control col' %>
  </div>

  <div class="form-group row">
    <span class="col-form-label col-3 col-md-3">Country: </span>
    <%= f.radio_button :country, 'us' %>
    <%= f.label :country, "United States", value: 'us', class: 'col-form-label col-4 col-md-3' %>
    <%= f.radio_button :country, 'canada' %>
    <%= f.label :country, "Canada", value: 'canada', class: 'col-form-label col-4 col-md-3' %>
  </div>

  <div class="form-group row">
    <%= f.label :birthday, class: 'col-form-label col-4 col-md-3' %>
    <%= f.date_field :birthday %>
  </div>

  <div class="form-group row">
    <%= f.label :color, class: 'col-form-label col-4 col-md-3' %>
    <%= f.color_field :color %>
  </div>

  <div class="form-group row">
    <%= f.label :age, class: 'col-form-label col-4 col-md-3' %>
    <%= f.number_field :age %>
  </div>

  <div class="form-group row">
    <%= f.label :website, class: 'col-form-label col-4 col-md-3' %>
    <%= f.url_field :website %>
  </div>

  <div class="form-group row">
    <%= f.label :picture, class: 'col-form-label col-4 col-md-3' %>
    <%= f.file_field :picture %>
  </div>

  <div class="form-group row">
    <%= f.label :phone, class: 'col-form-label col-4 col-md-3' %>
    <%= f.phone_field :phone %>
  </div>

  <div class="form-group row">
    <span class="col-form-label col-4 col-md-3">Common Interests</span>
    <%= f.check_box :interest_climb %>
    <%= f.label :interest_climb, "Climbing", class: 'col-form-label col-3 col-md-2' %>
    <%= f.check_box :interest_dance %>
    <%= f.label :interest_dance, "Dancing", class: 'col-form-label col-3 col-md-2' %>
    <%= f.check_box :interest_read %>
    <%= f.label :interest_read, "Reading", class: 'col-form-label col-3 col-md-2' %>
  </div>

  <div class="form-group row">
    <%= f.label :note, class: 'col-form-label col-4 col-md-3' %>
    <%= f.text_area :note, class: 'form-control col', rows: '3' %>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: 'btn btn-primary', data: {test: 'submit'} %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h2>Editing Address</h2>

<%= render 'form', address: @address %>

<div class="row justify-content-center">
<%= link_to 'Show', @address, data: {test: 'show'} %>
  &nbsp; | &nbsp;
<%= link_to 'List', addresses_path, data: {test: 'list'} %>
</div>

app/views/addresses/index.html.erb
<h2>Addresses</h2>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.first_name %></td>
        <td><%= address.last_name %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= link_to 'Show', address, data: {test: "show-#{address.id}"} %></td>
        <td><%= link_to 'Edit', edit_address_path(address), data: {test: "edit-#{address.id}"} %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?', test: "destroy-#{address.id}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path, class: 'row justify-content-center', data: {test: 'create'} %>

app/views/addresses/new.html.erb
<h2>New Address</h2>

<div class="row justify-content-center">
  <div class="col-sm-8">
    <%= render 'form', address: @address %>
  </div>
</div>

<%= link_to 'List', addresses_path, class: 'row justify-content-center', data: {test: 'list'} %>

app/views/addresses/show.html.erb
<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>First name: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="first_name"> <%= @address.first_name %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Last name: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="last_name"> <%= @address.last_name %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Street Address: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="street_address"> <%= @address.address1 %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Secondary Address: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="secondary_address"> <%= @address.address2 %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>City: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="city"> <%= @address.city %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>State: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="state"> <%= @address.state %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Zip code: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="zip_code"> <%= @address.zip_code %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Country: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="country"> <%= @address.country %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Birthday: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="birthday"> <%= @address.birthday.strftime("%-m/%d/%Y") if @address.birthday %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Color: </strong></span>
  <span data-test="color" style="width: 25px; height: 25px; background: <%= @address.color %>"></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Age: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="age"> <%= @address.age %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Website: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="website"> <%= @address.website %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Phone: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="phone"> <%= number_to_phone @address.phone %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Climbing? </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="interest_climb"> <%= @address.interest_climb ? "Yes" : "No" %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Dancing? </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="interest_dance"> <%= @address.interest_dance ? "Yes" : "No" %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Reading? </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="interest_read"> <%= @address.interest_read ? "Yes" : "No" %></span>
</p>

<p class="row no-gutters">
  <span class="col-3 col-md-2"><strong>Note: </strong></span>
  <span class="col offset-1 offset-sm-0" data-test="note"><%= @address.note %></span>
</p>

<div class="row justify-content-center">
  <%= link_to 'Edit', edit_address_path(@address), data: {test: 'edit'} %>
  &nbsp; | &nbsp;
  <%= link_to 'List', addresses_path, data: {test: 'list'} %>
</div>

app/views/layouts/_bootstrap_foot.html.erb
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

app/views/layouts/_bootstrap_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}", data: {test: 'notice'}) %>
<% end %>

app/views/layouts/_ie.html.erb
<meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv/min.js"></script>
<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <div class="navbar-nav mr-auto">
      <%= link_to root_path, class: "nav-item nav-link active", data: {test: 'home'} do %>
          Home
          <span class="sr-only">(current)</span>
      <% end %>
      <% if signed_in? %>
          <%= link_to 'Addresses', addresses_path, class: 'nav-item nav-link', data: {test: 'addresses'} %>
          <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'nav-item nav-link', data: {test: 'sign-out'} %>
      <% else %>
          <%= link_to 'Sign in', sign_in_path, id: "sign-in", class: "nav-item nav-link", data: {test: 'sign-in'} %>
      <% end %>
    </div>

    <div>
      <% if signed_in? %>
        <span class="navbar-text" data-test="current-user"><%= current_user.email %></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= "Address Book" + (" - " + yield(:title) unless yield(:title).blank?).to_s %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/ie' %>
    <%= render 'layouts/bootstrap_head' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  <%= render 'layouts/bootstrap_foot' %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="text-center">
  <h1>Welcome to Address Book</h1>
  <br />
  <h4>
    A simple web app for showing off your testing
  </h4>

</div>

app/views/users/_form.html.erb
<div class="form-group row">
  <%= form.text_field :email, type: 'email', class: 'form-control', placeholder: 'Email', data: {test: 'email'} %>
</div>

<div class="form-group row">
  <%= form.password_field :password, class: 'form-control', placeholder: 'Password', data: {test: 'password'} %>
</div>

app/views/users/new.html.erb
<% content_for :title, "Sign Up" %>
<div id="clearance" class="sign-up">
  <h2 class="text-center"><%= t(".title") %></h2>

  <div class="row justify-content-center">
    <div class="col-sm-8 col-md-6 col-lg-4">
      <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="form-group row">
      <%= form.submit class: 'btn btn-primary', data: {test: 'submit'} %>
    </div>

    <div class="row">
      <%= link_to t(".sign_in"), sign_in_path, data: {test: 'sign-in'} %>
    </div>
  <% end %>
    </div>
  </div>
</div>